name: 🐛 프로젝트 버그
description: 프로젝트를 따라하던 도중 마주친 버그를 제보합니다.
title: '[프로젝트버그] '
labels: ['bug']
assignees:
  - hwasurr
body:
  - type: markdown
    attributes:
      value: 먼저, 제보에 감사합니다!🥰

  - type: input
    validations:
      required: true
    attributes:
      label: '🐛 버그가 발견된 페이지'
      description: '버그가 발견된 내용이 포함된 쪽수를 알려주세요.'
      placeholder: 예) 97p ~ 102p

  - type: textarea
    validations:
      required: true
    attributes:
      label: '🐞 버그를 설명해주세요.'
      description: '발생한 버그 내용을 자세히 알려주세요.'
      placeholder: |
        예) npm 설치 이후 npm 명령어가 올바르게 작동하지 않습니다.

  - type: textarea
    validations:
      required: true
    attributes:
      label: '🍉 버그를 재현할 방법을 알려주세요'
      description: '버그를 재현할 방법을 알려주세요. 가능하다면 순서를 알려주세요!'
      placeholder: |
        예)
        1. npm 설치
        2. npm -v 시도했을 때 명령어를 찾을 수 없음.

  - type: checkboxes
    validations:
      required: true
    attributes:
      label: '🌏 오류가 발생한 환경의 OS는 무엇인가요?'
      options:
        - label: macOS
        - label: Windows
        - label: Linux
